### ISSUE TITLE
Add license, contributing, gh template, and changelog files

### ISSUE THREAD

**Issue by jstockwin** [jstockwin/py-pdf-parser#49]
We should add:
- [x] a license
- [ ] a contributing.md
- [ ] github template files for:
  - [ ] issue - bug
  - [ ] issue - feature request
  - [ ] pull request
- [x] changelog (https://github.com/optimor/py-pdf-parser/pull/61)
